### ISSUE TITLE
Webhook Sentry might be deleting request body somehow?

### ISSUE THREAD

**Issue by mlissner** [juggernaut/webhook-sentry#15]
This one is a long shot, but we're pretty baffled about it, so I'm writing it down here in case it rings a bell with you, @juggernaut, or perhaps somebody else. 

We're using Webhook Sentry in a k8s environment. Every so often, a request goes into Webhook Sentry with a request body, but arrives at our webhook endpoint without it. Somewhere along the line the request body is being stripped.

The full process looks like this:
1. Our application layer creates a webhook POST with a body.
2. An assertion is checked just before the next step, to ensure the request has a body.
3. The request is posted to Webhook Sentry, which proxies it to our webhook endpoint of a different service.
4. Our webhook endpoint checks `request.json`, but it's empty.
5. Our webhook endpoint therefore crashes and throws an HTTP error.
6. The application layer from step 1 catches the error and retries the webhook.
7. It works.

We aim to send a high volume of webhook events, so we want to track this down. After having this error happen a few times, we put an assertion at step 2 above to make sure that we weren't sending empty bodies. Today, we had the error happen again, meaning that the assertion passed, but somehow the webhook endpoint didn't get data on step 4.

I'm entirely open to the possibility that there's something in our network layer causing this, but:
 - It would be weird for an encrypted request to be modified in transit.
 - We don't have anything particularly weird in our network layer.

We're at a bit of a loss. Data is going into the network OK—it passes the assertion—but is somehow vanishing along the way. Does this make any sense to you or maybe ring any bells? Is it something that a bug in Webhook Sentry could cause? 

If you have any ideas for how to look into this, we'd be happy to try to help debug/fix it. We're motivated on this one! Thank you! 

We're tracking [the issue here](https://github.com/freelawproject/bigcases2/issues/128).

**Comment by juggernaut** [comment]
That seems strange @mlissner . I haven't encountered this issue so far. So that I can attempt to reproduce on my end, can you please provide the following info:
1. Headers and request params passed to webhook-sentry
2. Approximate size of request body
3. webhook-sentry config
4. Does it happen only under load, or even when there is zero to no load?

Thanks!

**Comment by albertisfu** [comment]
Thanks @juggernaut  here are the details about the issue:

> 1.- Headers and request params passed to webhook-sentry:

These are the headers we're sending to webhook proxy:
```
"Content-type": "application/json"
"Idempotency-Key": An uuid string used by the client to identify the uniqueness of the request.
"X-WhSentry-TLS": "true"
```

And the request is made with the following params:

We're using Python `requests` module:

```
proxy_server = {
        "http": "http://cl-webhook-sentry:9090",  #The proxy URL.
    }
requests.post(
            url,
            proxies=proxy_server,
            json=json_data,
            timeout=(3, 3),
            stream=True,
            headers=headers,
            allow_redirects=False,
        )
```

The `url` param here is changed in order to use the `http` protocol as described in [documentation](https://github.com/juggernaut/webhook-sentry#https-target) 

> 2. Approximate size of request body

Here are some sizes of the request body from different events that failed:

8,551 bytes
90,293 bytes
18,314 bytes
10,252 bytes
12,278 bytes 
11,841 bytes

In the end, events usually succeed after some retries.
I checked many events in which the delivery succeeded on the first attempt, and the average size is approximately 3,000 bytes. Interestingly, I've not encountered an event where this issue occurred with a size of less than 8,000 bytes. It is uncertain whether this is merely a coincidence.

> 3. webhook-sentry config

We're using the docker image` juggernaut/webhook-sentry:v1.1.0` with the default `config.go` file.

In case is helpful this is the k8s config:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cl-webhook-sentry
  namespace: court-listener
  labels:
    service: cl-webhook-sentry
spec:
  replicas: 2
  selector:
    matchLabels:
      service: cl-webhook-sentry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: cl-webhook-sentry
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: static-egress-node-group
      containers:
        - name: webhook-sentry
          image: juggernaut/webhook-sentry:v1.1.0
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 9090
          livenessProbe:
            periodSeconds: 5
            httpGet:
              path: /metrics
              port: 2112


---
apiVersion: v1
kind: Service
metadata:
  name: cl-webhook-sentry
  namespace: court-listener
  labels:
    service: cl-webhook-sentry
spec:
  selector:
    service: cl-webhook-sentry
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

```

> 4. Does it happen only under load, or even when there is zero to no load?

At the moment, we are not experiencing a high load, as we are sending no more than 15 events per hour. Today's error occurred during a period of low load; it was the only event sent at that time. There was a successful event two minutes prior and another one ten minutes later.


Finally, I'm not sure if this might be related but I noticed a similar issue sending events to an HTTPS `ngrok` endpoint using `webhook-sentry` with `X-WhSentry-TLS` header set to True, the headers are properly received but the data is empty.


Thank you!
